<a href="https://colab.research.google.com/github/asadaligadehi/DataScience/blob/main/lab_04_20sw042.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

LAB : 04 o How to import NumPy

o How to create multidimensional NumPy ndarrays using various methods

o How to access and change elements in ndarrays

o How to load and save ndarrays

o How to use slicing to select or change subsets of an ndarray

o Understand the difference between a view and a copy an of ndarray

o How to use Boolean indexing and set operations to select or change subsets of an ndarray

o How to sort ndarrays

o How to perform element-wise operations on ndarrays

o Understand how NumPy uses broadcasting to perform operations on ndarrays of different sizes.

Roll no : 20SW042

Section : 2

Task#01

In [1]:
import numpy as np

# Generate an array of even numbers from 2 to 32 (inclusive)
even_numbers = np.arange(2, 33, 2)

# Reshape the array into a 4x4 ndarray
X = even_numbers.reshape(4, 4)

print(X)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


Task#02

In [2]:
import numpy as np

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
X = np.arange(1, 26).reshape(5, 5)

# Use Boolean indexing to pick out only the odd numbers in the array
Y = X[X % 2 == 1]

print("Original array X:\n", X)
print("\nArray Y with odd numbers:\n", Y)

Original array X:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Array Y with odd numbers:
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25]


Task#03

In [3]:
import numpy as np

# Create a 4 x 4 ndarray with columns filled with increasing values
# using broadcasting
X = np.arange(1, 5)[:, np.newaxis] * np.ones((4, 4))

print(X)

[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


Task#04

In [4]:
import numpy as np

# Create a random permutation of integers 0 to 4
permuted_indices = np.random.permutation(5)

# Create a 1000 x 20 ndarray with random integers in the half-open interval [0, 5001).
X = np.random.randint(0, 5001, size=(1000, 20))

# Create a rank 1 ndarray that contains a random permutation of the row indices of `X`
row_indices = np.random.permutation(X.shape[0])

# Make any necessary calculations.
# You can save your calculations into variables to use later.

# Create a Training Set
X_train = X[row_indices[:700], :]

# Create a Cross Validation Set
X_crossVal = X[row_indices[700:850], :]

# Create a Test Set
X_test = X[row_indices[850:], :]

# Print the shape of X_train
print("Shape of X_train:", X_train.shape)

# Print the shape of X_crossVal
print("Shape of X_crossVal:", X_crossVal.shape)

# Print the shape of X_test
print("Shape of X_test:", X_test.shape)

Shape of X_train: (700, 20)
Shape of X_crossVal: (150, 20)
Shape of X_test: (150, 20)


Task#05

In [5]:
import numpy as np

# Create a 1000 x 20 ndarray with random integers in the half-open interval [0, 5001).
X = np.random.randint(0, 5001, size=(1000, 20))

# Print the shape of X
print("Shape of X:", X.shape)

# Average of the values in each column of X
ave_cols = np.mean(X, axis=0)

# Standard Deviation of the values in each column of X
std_cols = np.std(X, axis=0)

# Print the shape of ave_cols
print("Shape of ave_cols:", ave_cols.shape)

# Print the shape of std_cols
print("Shape of std_cols:", std_cols.shape)

# Mean normalize X
X_norm = (X - np.mean(X, axis=0)) / np.std(X, axis=0)

# Print the average of all the values of X_norm
print("Average of all values in X_norm:", np.mean(X_norm))

# Print the average of the minimum value in each column of X_norm
print("Average of minimum values in each column of X_norm:", np.mean(np.min(X_norm, axis=0)))

# Print the average of the maximum value in each column of X_norm
print("Average of maximum values in each column of X_norm:", np.mean(np.max(X_norm, axis=0)))

Shape of X: (1000, 20)
Shape of ave_cols: (20,)
Shape of std_cols: (20,)
Average of all values in X_norm: 2.6822988274943783e-17
Average of minimum values in each column of X_norm: -1.724986822402467
Average of maximum values in each column of X_norm: 1.736102891179155
